language: python
python:
  - "2.7"
script:
  - ls -al 	
  - sudo apt-get install python-pip
  - sudo apt-get install python-dev 
  - sudo apt-get install libxml2-dev
  - sudo apt-get install libxslt-dev
  - sudo apt-get install libssl-dev
  - sudo apt-get install libffi-dev
  - sudo apt-get install python-pip
  - sudo apt-get install ansible
  - pip install junos-eznc	
  - ls 
  - pwd
  - cd sample_ospf*
  - python *.py
  - cd ../sample_bgp* 
  - python *.py
sudo:
- required

deploy:
  provider: pages
  skip-cleanup: true
  github-token: klD4Oh3NlO735v8T4MPwww  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: deployment

